# Sequence to Sequence (seq2seq) Recurrent Neural Network (RNN) for Time Series Prediction

The goal of this project of mine is to bring users to try and experiment with the seq2seq neural network architecture. This is done by solving different simple toy problems about signal prediction. Normally, seq2seq architectures may be used for other more sophisticated purposes than for signal prediction, let's say, language modeling, but this project is an interesting tutorial in order to then get to more complicated stuff. 

In this project are given 4 exercises of gradually increasing difficulty. I take for granted that the public already have at least knowledge of basic RNNs and how can they be shaped into an encoder and a decoder of the most simple form (without attention). To learn more about RNNs in TensorFlow, you may want to visit this other project of mine about that: https://github.com/guillaume-chevalier/LSTM-Human-Activity-Recognition

The current project is a series of example I have first built in French, but I haven't got the time to generate all the charts anew with proper English text. I have built this project for the practical part of the third hour of a "master class" conference that I gave at the WAQ (Web At Quebec) in March 2017: 
https://webaquebec.org/classes-de-maitre/deep-learning-avec-tensorflow

You can find the French, original, version of this project in the French Git branch: https://github.com/guillaume-chevalier/seq2seq-signal-prediction/tree/francais

## How to use this ".ipynb" Python notebook ?

Except the fact I made available an ".py" Python version of this tutorial within the repository, it is more convenient to run the code inside the notebook. The ".py" code exported feels a bit raw as an exportation. 

To run the notebook, you must have installed Jupyter Notebook or iPython Notebook. To open the notebook, you must write `jupyter notebook` or `iPython notebook` in command line (from the folder containing the notebook once downloaded, or a parent folder). It is then that the notebook application (IDE) will open in your browser as a local server and it will be possible to open the `.ipynb` notebook file and to run code cells with `CTRL+ENTER` and `SHIFT+ENTER`, it is also possible to restart the kernel and run all cells at once with the menus. Note that this is interesting since it is possible to make that IDE run as hosted on a cloud server with a lot of GPU power while you code through the browser.

## Exercises

Note that the dataset changes in function of the exercice. Most of the time, you will have to edit the neural networks' training parameter to succeed in doing the exercise, but at a certain point, changes in the architecture itself will be asked and required. The datasets used for this exercises are found in `datasets.py`.

### Exercise 1

In theory, it is possible to create a perfect prediction of the signal for this exercise. The neural network's parameters has been set to acceptable values for a first training, so you may pass this exercise by running the code without even a change. Your first training might get predictions like that (in yellow), but it is possible to do a lot better with proper parameters adjustments:

<img src="images/E1.png" />

Note: the neural network sees only what is to the left of the chart and is trained to predict what is at the right (predictions in yellow). 

We have 2 time series at once to predict, which are tied together. That means our neural network processes multidimensional data. A simple example would be to receive as an argument the past values of multiple stock market symbols in order to predict the future values of all those symbols with the neural network, which values are evolving together in time. That is what we will do in the exercise 6. 


### Exercise 2

Here, rather than 2 signals in parallel to predict, we have only one, for simplicity. HOWEVER, this signal is a superposition of two sine waves of varying wavelenght and offset (and restricted to a particular min and max limit of wavelengts). 

In order to finish this exercise properly, you will need to edit the neural network's hyperparameters. As an example, here is what is possible to achieve as a predction with those better (but still unperfect) training hyperparameters: 

- `nb_iters = 2500`
- `batch_size = 50`
- `hidden_dim = 35`
<img src="images/E2.png" />

Here are predictions achieved with a bigger neural networks with 3 stacked recurrent cells and a width of 500 hidden units for each of those cells: 

<img src="images/E2_1.png" />

<img src="images/E2_2.png" />

<img src="images/E2_3.png" />

<img src="images/E2_4.png" />

Note that it would be possible to obtain better results with a smaller neural network, provided better training hyperparameters and a longer training, adding dropout, and on. 

### Exercise 3

This exercise is similar to the previous one, except that the input data given to the encoder is noisy. The expected output is not noisy. This makes the task a bit harder. Here is a good example of what a training example (and a prediction) could now looks like :

<img src="images/E3.png" />

Therefore the neural network is brought to denoise the signal to interpret its future smooth values. Here are some example of better predictions on this version of the dataset : 

<img src="images/E3_1.png" />

<img src="images/E3_2.png" />

<img src="images/E3_3.png" />

<img src="images/E3_4.png" />

Similarly as I said for the exercise 2, it would be possible here too to obtain better results. Note that it would also have been possible to ask you to predict to reconstruct the denoised signal from the noisy input (and not predict the future values of it). This would have been called a "denoising autoencoder", this type of architecture is also useful for data compression, such as manipulating images. 

### Exercise 4

This exercise is much harder than the previous ones and is built more as a suggestion. It is to predict the future value of the Bitcoin's price. We have here some daily market data of the bitcoin's value, that is, BTC/USD and BTC/EUR. This is not enough to build a good predictor, at least having data precise at the minute level, or second level, would be more interesting. Here is a prediction made on the actual future values, the neural network has not been trained on the future values shown here and this is a legitimate prediction, given a well-enough model trained on the task: 

<img src="images/E5.png" />

Disclaimer: this prediction of the future values was really good and you should not expect predictions to be always that good using as few data as actually (side note: the other prediction charts in this project are all "average" except this one). Your task for this exercise is to plug the model on more valuable financial data in order to make more accurate predictions. Let me remind you that I provided the code for the datasets in "datasets.py", but that should be replaced for predicting accurately the Bitcoin. 

It would be possible to improve the input dimensions of your model that accepts (BTC/USD and BTC/EUR). As an example, you could create additionnal input dimensions/streams which could contain meteo data and more financial data, such as the S&P 500, the Dow Jones, and on. Other more creative input data could be sine waves (or other-type-shaped waves such as saw waves or triangles or two signals for `cos` and `sin`) representing the fluctuation of minutes, hours, days, weeks, months, years, moon cycles, and on. This could be combined with a Twitter sentiment analysis about the word "Bitcoin" in tweets in order to have another input signal which is more human-based and abstract. Actually, some libraries exists to convert text to a sentiment value, and there would also be the neural network end-to-end approach (but that would be a way more complicated setup). It is also interesting to know where is the bitcoin most used: http://images.google.com/search?tbm=isch&q=bitcoin+heatmap+world

With all the above-mentionned examples, it would be possible to have all of this as input features, at every time steps: (BTC/USD, BTC/EUR, Dow_Jones, SP_500, hours, days, weeks, months, years, moons, meteo_USA, meteo_EUROPE, Twitter_sentiment). Finally, there could be those two output features, or more: (BTC/USD, BTC/EUR). 

This prediction concept can apply to many things, such as meteo prediction and other types of shot-term and mid-term statistical predictions. 

## To change which exercise you are doing, change the value of the following "exercise" variable:


In [2]:

exercise = 1  # Possible values: 1, 2, 3, or 4.

from datasets import generate_x_y_data_v1, generate_x_y_data_v2, generate_x_y_data_v3, generate_x_y_data_v4 

# We choose which data function to use below, in function of the exericse. 
if exercise == 1:
    generate_x_y_data = generate_x_y_data_v1
if exercise == 2:
    generate_x_y_data = generate_x_y_data_v2
if exercise == 3:
    generate_x_y_data = generate_x_y_data_v3
if exercise == 4:  
    generate_x_y_data = generate_x_y_data_v4


In [3]:

import tensorflow as tf  # Version 1.0 or 0.12
import numpy as np
import matplotlib.pyplot as plt

# This is for the notebook to generate inline matplotlib 
# charts rather than to open a new window every time: 
%matplotlib inline


C:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


## Neural network's hyperparameters

In [ ]:
print  (sample_x)

In [4]:

exercise = 1  # Possible values: 1, 2, 3, or 4.

from datasets import generate_x_y_data_v1, generate_x_y_data_v2, generate_x_y_data_v3, generate_x_y_data_v4 

# We choose which data function to use below, in function of the exericse. 
if exercise == 1:
    generate_x_y_data = generate_x_y_data_v1


sample_x, sample_y = generate_x_y_data(isTrain=True, batch_size=1)
print("Dimensions of the dataset for 3 X and 3 Y training examples : ")
print(sample_x.shape)
print(sample_y.shape)
print("(seq_length, batch_size, output_dim)")

# Internal neural network parameters
seq_length = sample_x.shape[0]  # Time series will have the same past and future (to be predicted) lenght. 
batch_size = 5  # Low value used for live demo purposes - 100 and 1000 would be possible too, crank that up!

output_dim = input_dim = sample_x.shape[-1]  # Output dimension (e.g.: multiple signals at once, tied in time)
hidden_dim = 12  # Count of hidden neurons in the recurrent units. 
layers_stacked_count = 2  # Number of stacked recurrent cells, on the neural depth axis. 

# Optmizer: 
learning_rate = 0.007  # Small lr helps not to diverge during training. 
nb_iters = 150  # How many times we perform a training step (therefore how many times we show a batch). 
lr_decay = 0.92  # default: 0.9 . Simulated annealing.
momentum = 0.5  # default: 0.0 . Momentum technique in weights update
lambda_l2_reg = 0.003  # L2 regularization of weights - avoids overfitting


Dimensions of the dataset for 3 X and 3 Y training examples : 
(10, 1, 3)
(10, 1, 3)
(seq_length, batch_size, output_dim)


In [ ]:
print (input_dim)

## Definition of the seq2seq neuronal architecture

<img src="https://www.tensorflow.org/images/basic_seq2seq.png" />

Comparatively to what we see in the image, our neural network deals with signal rather than letters. Also, we don't have the feedback mechanism yet. 

In [5]:

# Backward compatibility for TensorFlow's version 0.12: 
try:
    tf.nn.seq2seq = tf.contrib.legacy_seq2seq
    tf.nn.rnn_cell = tf.contrib.rnn
    tf.nn.rnn_cell.GRUCell = tf.contrib.rnn.GRUCell
    print("TensorFlow's version : 1.0 (or more)")
except: 
    print("TensorFlow's version : 0.12")


TensorFlow's version : 1.0 (or more)


In [6]:

tf.reset_default_graph()
# sess.close()
sess = tf.InteractiveSession()

with tf.variable_scope('Seq2seq'):

    # Encoder: inputs
    enc_inp = [
        tf.placeholder(tf.float32, shape=(None, input_dim), name="inp_{}".format(t))
           for t in range(seq_length)
    ]

    # Decoder: expected outputs
    expected_sparse_output = [
        tf.placeholder(tf.float32, shape=(None, output_dim), name="expected_sparse_output_".format(t))
          for t in range(seq_length)
    ]
    
    # Give a "GO" token to the decoder. 
    # Note: we might want to fill the encoder with zeros or its own feedback rather than with "+ enc_inp[:-1]"
    dec_inp = [ tf.zeros_like(enc_inp[0], dtype=np.float32, name="GO") ] + enc_inp[:-1]

    # Create a `layers_stacked_count` of stacked RNNs (GRU cells here). 
    cells = []
    for i in range(layers_stacked_count):
        with tf.variable_scope('RNN_{}'.format(i)):
            cells.append(tf.nn.rnn_cell.GRUCell(hidden_dim))
            # cells.append(tf.nn.rnn_cell.BasicLSTMCell(...))
    cell = tf.nn.rnn_cell.MultiRNNCell(cells)
    
    # Here, the encoder and the decoder uses the same cell, HOWEVER,
    # the weights aren't shared among the encoder and decoder, we have two
    # sets of weights created under the hood according to that function's def. 
    dec_outputs, dec_memory = tf.nn.seq2seq.basic_rnn_seq2seq(
        enc_inp, 
        dec_inp, 
        cell
    )
    
    # For reshaping the output dimensions of the seq2seq RNN: 
    w_out = tf.Variable(tf.random_normal([hidden_dim, output_dim]))
    b_out = tf.Variable(tf.random_normal([output_dim]))
    
    # Final outputs: with linear rescaling for enabling possibly large and unrestricted output values.
    output_scale_factor = tf.Variable(1.0, name="Output_ScaleFactor")
    
    reshaped_outputs = [output_scale_factor*(tf.matmul(i, w_out) + b_out) for i in dec_outputs]


In [7]:

# Training loss and optimizer

with tf.variable_scope('Loss'):
    # L2 loss
    output_loss = 0
    for _y, _Y in zip(reshaped_outputs, expected_sparse_output):
        output_loss += tf.reduce_mean(tf.nn.l2_loss(_y - _Y))
                
    # L2 regularization (to avoid overfitting and to have a  better generalization capacity)
    reg_loss = 0
    for tf_var in tf.trainable_variables():
        if not ("Bias" in tf_var.name or "Output_" in tf_var.name):
            reg_loss += tf.reduce_mean(tf.nn.l2_loss(tf_var))
            
    loss = output_loss + lambda_l2_reg * reg_loss

with tf.variable_scope('Optimizer'):
    optimizer = tf.train.RMSPropOptimizer(learning_rate, decay=lr_decay, momentum=momentum)
    train_op = optimizer.minimize(loss)


## Training of the neural net

In [9]:

def train_batch(batch_size):
    """
    Training step that optimizes the weights 
    provided some batch_size X and Y examples from the dataset. 
    """
    X, Y = generate_x_y_data(isTrain=True, batch_size=batch_size)
    feed_dict = {enc_inp[t]: X[t] for t in range(len(enc_inp))}
    feed_dict.update({expected_sparse_output[t]: Y[t] for t in range(len(expected_sparse_output))})
    _, loss_t, __y, __Y = sess.run([train_op, loss, _y, _Y], feed_dict)
    print (__y, __Y)
    #print(expected_sparse_output)
    
    return loss_t

def test_batch(batch_size):
    """
    Test step, does NOT optimizes. Weights are frozen by not
    doing sess.run on the train_op. 
    """
    X, Y = generate_x_y_data(isTrain=False, batch_size=batch_size)
    feed_dict = {enc_inp[t]: X[t] for t in range(len(enc_inp))}
    feed_dict.update({expected_sparse_output[t]: Y[t] for t in range(len(expected_sparse_output))})
    loss_t = sess.run([loss], feed_dict)
    return loss_t[0]


# Training
train_losses = []
test_losses = []

sess.run(tf.global_variables_initializer())
for t in range(nb_iters+1):
    train_loss = train_batch(batch_size)
    train_losses.append(train_loss)
    
    if t % 10 == 0: 
        # Tester
        test_loss = test_batch(batch_size)
        test_losses.append(test_loss)
        print("Step {}/{}, train loss: {}, \tTEST loss: {}".format(t, nb_iters, train_loss, test_loss))

print("Fin. train loss: {}, \tTEST loss: {}".format(train_loss, test_loss))


[[-0.10714492  1.9369652  -0.02967274]
 [-0.23263974  2.232553    0.22289598]
 [-0.21387403  2.0106933  -0.04849446]
 [ 0.07914394  1.8800364   0.13305533]
 [ 0.16360141  1.8691401   0.2343384 ]] [[-0.31615248  0.9487084   0.05      ]
 [ 0.8192923   0.57337606  0.05      ]
 [ 0.07628017  0.9970864   0.05      ]
 [-0.7046325   0.70957243  0.05      ]
 [-0.8206672   0.5714065   0.05      ]]
Step 0/150, train loss: 156.17044067382812, 	TEST loss: 43.00661849975586
[[ 0.52245194  0.43745917  0.15910539]
 [ 0.49067086  0.89840984  0.3619839 ]
 [ 0.54855454  0.5529071   0.25190789]
 [-0.2808097   0.7604305  -0.42643803]
 [-0.22183427  0.6265678  -0.49593258]] [[-0.88940936 -0.45711157  0.05      ]
 [-0.21050152 -0.97759354  0.05      ]
 [-0.7418114  -0.6706086   0.05      ]
 [ 0.2739765   0.9617364   0.05      ]
 [-0.01140328  0.999935    0.05      ]]
[[ 9.40770805e-02 -7.79223859e-01 -5.23455262e-01]
 [ 3.69773060e-01 -1.96577266e-01 -2.02921759e-02]
 [ 2.42012277e-01  7.24082440e-02  1.316

[[ 0.85766697  0.54552215  0.03973906]
 [ 1.0088384   0.2591399  -0.00915555]
 [-0.7721873  -0.7059916   0.06725597]
 [-0.25506058 -1.0238421  -0.0429623 ]
 [-1.0266513   0.78012997  0.12884392]] [[ 0.8760872   0.48215276  0.05      ]
 [ 0.9862526   0.16524458  0.05      ]
 [-0.750742   -0.6605955   0.05      ]
 [-0.33450398 -0.9423943   0.05      ]
 [-0.81936985  0.5732653   0.05      ]]
[[ 0.881346   -0.7582969  -0.11093807]
 [-0.52104294 -1.0091174  -0.02359861]
 [ 1.0720958  -0.1075213  -0.07210337]
 [-0.5861277   0.8843853   0.04105606]
 [ 0.05257235  0.91195565  0.06156435]] [[ 0.71555245 -0.698559    0.05      ]
 [-0.57473576 -0.81833905  0.05      ]
 [ 0.9978744  -0.06516714  0.05      ]
 [-0.48038134  0.87705976  0.05      ]
 [ 0.09516819  0.9954612   0.05      ]]
[[-0.39894697 -1.0211514   0.01495828]
 [-1.0843388  -0.01895826  0.1373635 ]
 [-1.0490186  -0.22646172  0.13965581]
 [-0.8228924   0.74756324  0.07428933]
 [-0.32509527 -1.0499141   0.00358871]] [[-0.44076067 -0.897

[[ 0.2309146   0.96033007  0.07142384]
 [-0.888791    0.6195763   0.08187491]
 [ 0.8779136   0.46308756  0.02045865]
 [-0.8551056   0.6670313   0.07707762]
 [-0.84169513 -0.6322582   0.10688677]] [[ 0.19488227  0.9808266   0.05      ]
 [-0.86446357  0.5026955   0.05      ]
 [ 0.877972    0.478712    0.05      ]
 [-0.8343217   0.55127794  0.05      ]
 [-0.7601123  -0.6497918   0.05      ]]
[[ 0.5555098  -1.002906   -0.01187197]
 [ 0.72448516  0.64153636  0.02958235]
 [ 0.9420315  -0.5364156  -0.02135513]
 [ 0.8237057   0.53662115  0.01629649]
 [ 0.99422765  0.21749137 -0.01441174]] [[ 0.46406668 -0.8858003   0.05      ]
 [ 0.709055    0.70515317  0.05      ]
 [ 0.86067027 -0.50916266  0.05      ]
 [ 0.81085694  0.5852444   0.05      ]
 [ 0.9737284   0.2277124   0.05      ]]
[[-0.35109654  0.97215694  0.17113562]
 [ 0.3237962   0.96021855  0.20024401]
 [ 0.7295643   0.6930138   0.17121103]
 [ 0.92874146  0.35516566  0.13556427]
 [ 0.70617557  0.7177899   0.17432305]] [[-0.2938554   0.955

 [ 0.7609991  -0.77978295  0.14859918]] [[ 0.8576853  -0.514175    0.05      ]
 [ 0.995071   -0.09916496  0.05      ]
 [ 0.58876044  0.8083076   0.05      ]
 [ 0.67264414 -0.73996615  0.05      ]
 [ 0.709561   -0.704644    0.05      ]]
[[ 0.6589809  -0.77854955  0.05688829]
 [ 0.65197307 -0.78614783  0.05712326]
 [-0.9825136  -0.02630697  0.09860554]
 [ 0.41093826 -0.97488296  0.06023875]
 [-0.642083   -0.87079924  0.10119371]] [[ 0.6478984  -0.7617268   0.05      ]
 [ 0.6406556  -0.76782835  0.05      ]
 [-0.9997245   0.02347098  0.05      ]
 [ 0.39984474 -0.9165829   0.05      ]
 [-0.6414476  -0.76716685  0.05      ]]
Step 70/150, train loss: 0.5890729427337646, 	TEST loss: 0.6258145570755005
[[ 0.775918   -0.60223186  0.05276651]
 [-0.7644989   0.7147223   0.01984126]
 [-0.17508341 -1.0902839   0.04915458]
 [ 0.27953556  0.9079537   0.03946094]
 [ 0.47951767 -0.9324087   0.05478447]] [[ 0.8482385  -0.5296144   0.05      ]
 [-0.7362457   0.67671436  0.05      ]
 [-0.06580469 -0.99783

Step 90/150, train loss: 0.5678241848945618, 	TEST loss: 0.6004126667976379
[[-0.67103934  0.7956205  -0.04024941]
 [ 0.81269306 -0.5702361   0.09511495]
 [ 0.47962052  0.85716385  0.01985152]
 [-0.8835152  -0.45026973  0.052175  ]
 [ 0.95061517 -0.1282262   0.06455217]] [[-0.69241834  0.7214963   0.05      ]
 [ 0.82231593 -0.5690312   0.05      ]
 [ 0.494244    0.8693232   0.05      ]
 [-0.8636909  -0.5040218   0.05      ]
 [ 0.9879422  -0.15482305  0.05      ]]
[[ 0.20203876 -1.0839151   0.13612288]
 [-0.9820722  -0.0788595   0.10433131]
 [-0.62588596  0.7561299   0.03554223]
 [ 0.8457506   0.4679131   0.0734833 ]
 [ 0.9401107  -0.34069857  0.11786874]] [[ 0.20834908 -0.9780545   0.05      ]
 [-0.99864954 -0.05195306  0.05      ]
 [-0.6513585   0.7587701   0.05      ]
 [ 0.87859404  0.47756934  0.05      ]
 [ 0.9472265  -0.32056496  0.05      ]]
[[-1.0152123   0.21953957  0.10527744]
 [ 0.82374203 -0.5235247   0.11665021]
 [ 0.93505156  0.23718967  0.07684854]
 [-0.55960643  0.894904

[[ 0.16497132 -1.0579126   0.07622175]
 [-0.9609563  -0.41707873  0.03573532]
 [-0.83392435 -0.6991509   0.04377664]
 [ 0.89572614 -0.345271    0.09346955]
 [ 0.741348    0.6758537   0.06876264]] [[ 0.13956566 -0.9902128   0.05      ]
 [-0.9584806  -0.28515768  0.05      ]
 [-0.8273832  -0.56163776  0.05      ]
 [ 0.89357316 -0.44891757  0.05      ]
 [ 0.8111266   0.5848707   0.05      ]]
Step 120/150, train loss: 0.5927363634109497, 	TEST loss: 0.4928937554359436
[[ 0.8344693   0.43960243  0.04748266]
 [ 0.02085377  0.9528089   0.04249745]
 [-0.7963192  -0.6915502   0.07074662]
 [-1.0012431   0.11363963  0.03195672]
 [ 0.3659318   0.88880444  0.05218482]] [[ 0.9338786   0.35759023  0.05      ]
 [ 0.04540955  0.9989685   0.05      ]
 [-0.7523932  -0.6587143   0.05      ]
 [-0.9879813   0.1545734   0.05      ]
 [ 0.4167686   0.9090126   0.05      ]]
[[ 0.64801455  0.73407423  0.08327799]
 [ 0.31887564  0.92267275  0.09947403]
 [-0.9912431  -0.05634962  0.14528495]
 [ 0.6240901   0.75525

Step 140/150, train loss: 0.8137954473495483, 	TEST loss: 0.8151288032531738
[[-0.9761071  -0.03672208  0.07924249]
 [ 0.60998785 -0.60583425  0.11149433]
 [ 0.6775722   0.60656846  0.08730429]
 [ 0.5367351  -0.67761177  0.11118323]
 [-0.3495401   0.9186198   0.06598531]] [[-0.99860734 -0.05275736  0.05      ]
 [ 0.7216464  -0.6922618   0.05      ]
 [ 0.81027645  0.5860479   0.05      ]
 [ 0.6431724  -0.7657214   0.05      ]
 [-0.30937696  0.9509395   0.05      ]]
[[ 0.43787393 -0.9861184   0.05454161]
 [-0.98474324 -0.23475279  0.03909736]
 [ 0.7880348   0.5433284   0.07344401]
 [ 0.20884913  0.94169164  0.08645986]
 [ 0.7751676   0.5624928   0.07436723]] [[ 0.49168152 -0.8707751   0.05      ]
 [-0.98613745 -0.16593051  0.05      ]
 [ 0.7995906   0.6005455   0.05      ]
 [ 0.18624604  0.9825031   0.05      ]
 [ 0.7852328   0.6192007   0.05      ]]
[[ 0.35726646  1.0335828   0.07651279]
 [-0.96049905 -0.23315854  0.14617369]
 [ 0.64156044  0.868803    0.06629754]
 [-0.0366688   1.11179

In [ ]:
print (_y)
print (_Y)

In [ ]:

# Plot loss over time:
plt.figure(figsize=(12, 6))
plt.plot(
    np.array(range(0, len(test_losses)))/float(len(test_losses)-1)*(len(train_losses)-1), 
    np.log(test_losses), 
    label="Test loss"
)
plt.plot(
    np.log(train_losses), 
    label="Train loss"
)
plt.title("Training errors over time (on a logarithmic scale)")
plt.xlabel('Iteration')
plt.ylabel('log(Loss)')
plt.legend(loc='best')
plt.show()


In [ ]:
print (X)


In [ ]:
# Test
nb_predictions = 1
#print("Let's visualize {} predictions with our signals:".format(nb_predictions))

X, Y = generate_x_y_data(isTrain=False, batch_size=nb_predictions)
feed_dict = {enc_inp[t]: X[t] for t in range(seq_length)}
outputs = np.array(sess.run([reshaped_outputs], feed_dict)[0])

for j in range(nb_predictions): 
    plt.figure(figsize=(12, 3))
    
    #print (X)
    
    for k in range(output_dim):
        past = X[:,j,k]   # ROB LOOK Here: j is batch number, k is feature (first or second)
        expected = Y[:,j,k]
        pred = outputs[:,j,k]
        
        label1 = "Seen (past) values" if k==0 else "_nolegend_"
        label2 = "True future values" if k==0 else "_nolegend_"
        label3 = "Predictions" if k==0 else "_nolegend_"
        plt.plot(range(len(past)), past, "o--b", label=label1)
        plt.plot(range(len(past), len(expected)+len(past)), expected, "x--b", label=label2)
        plt.plot(range(len(past), len(pred)+len(past)), pred, "o--y", label=label3)
        #print (past)
        
    plt.legend(loc='best')
    plt.title("Predictions v.s. true values")
    plt.show()

print("Reminder: the signal can contain many dimensions at once.")
print("In that case, signals have the same color.")
print("In reality, we could imagine multiple stock market symbols evolving,")
print("tied in time together and seen at once by the neural network.")

## Author

Guillaume Chevalier
- https://ca.linkedin.com/in/chevalierg
- https://twitter.com/guillaume_che
- https://github.com/guillaume-chevalier/

## License

This project is free to use according to the [MIT License](https://github.com/guillaume-chevalier/seq2seq-signal-prediction/blob/master/LICENSE) as long as you cite me and the License (read the License for more details). You can cite me by pointing to the following link: 
- https://github.com/guillaume-chevalier/seq2seq-signal-prediction

## Converting notebook to a readme file

In [ ]:
# Let's convert this notebook to a README for the GitHub project's title page:
!jupyter nbconvert --to markdown seq2seq.ipynb
!mv seq2seq.md README.md